---
micronaut:
  application:
    name: micronaut-exposed-starter

---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    driverClassName: org.postgresql.Driver
schema:
  gen: true
---
flyway:
  datasources:
    default:
      locations: src/main/resources/db