---
micronaut:
  application:
    name: micronaut-exposed-starter

---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    user: "postgres"
    password: "root"
    driverClassName: org.postgresql.Driver
---
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: postgres
      user: "postgres"
      password: "root"
      schema: news
      maxSize: 5
schema:
  gen: true